"""create insights_clusters table

Revision ID: 0f4aaec3786d
Revises: 9092f5cd7bd6
Create Date: 2025-10-29 18:37:34.006366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0f4aaec3786d'
down_revision: Union[str, Sequence[str], None] = '9092f5cd7bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights_clusters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vertical', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('n_posts', sa.Integer(), nullable=False),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_forum', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_clusters_vertical'), 'insights_clusters', ['vertical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_clusters_vertical'), table_name='insights_clusters')
    op.drop_table('insights_clusters')
    # ### end Alembic commands ###
