"""add insights_clusters table

Revision ID: 9092f5cd7bd6
Revises: 130722d2b736
Create Date: 2025-10-28 21:52:36.015051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '9092f5cd7bd6'
down_revision: Union[str, Sequence[str], None] = '130722d2b736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_sqlmodel', 'embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_sqlmodel', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=True)
    # ### end Alembic commands ###
