"""add embedding_attempt_at

Revision ID: efa29e790a51
Revises: 0f4aaec3786d
Create Date: 2025-11-09 19:26:44.812959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa29e790a51'
down_revision: Union[str, Sequence[str], None] = '0f4aaec3786d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_clusters_centroid'), table_name='insights_clusters', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(op.f('uq_insights_clusters_id'), 'insights_clusters', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_insights_clusters_id'), 'insights_clusters', ['id'])
    op.create_index(op.f('idx_clusters_centroid'), 'insights_clusters', ['centroid'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
